# Generated by Django 2.1.4 on 2019-01-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True, verbose_name='日付')),
                ('emo', models.IntegerField(max_length=6, verbose_name='エモ度')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='チーム作成日')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Day', verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=255, verbose_name='役職')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ユーザ名')),
                ('display_name', models.CharField(max_length=255, verbose_name='表示名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('team_num', models.IntegerField(max_length=255, verbose_name='チーム数')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.User', verbose_name='ユーザー'),
        ),
    ]
